package org.vitej.core.protocol.methods.response;

import org.joda.time.DateTime;
import org.vitej.core.protocol.methods.Address;
import org.vitej.core.protocol.methods.Hash;
import org.vitej.core.utils.BytesUtils;
import org.vitej.core.utils.TimeUtils;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;

/**
 * Snapshot block information
 */
public class SnapshotBlock {
    private String hash;
    private String previousHash;
    private Long height;
    private String producer;
    private String publicKey;
    private String signature;
    private BigInteger seed;
    private String nextSeedHash;
    private Integer version;
    private Map<String, HashHeight> snapshotData;
    private Long timestamp;

    /**
     * Return hash of snapshot block
     *
     * @return Hash of snapshot block
     */
    public Hash getHash() {
        return Hash.stringToHash(hash);
    }

    public String getHashRaw() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Return hash of previous snapshot block
     *
     * @return Hash of previous snapshot block
     */
    public Hash getPreviousHash() {
        return Hash.stringToHash(previousHash);
    }

    public String getPreviousHashRaw() {
        return previousHash;
    }

    public void setPreviousHash(String previousHash) {
        this.previousHash = previousHash;
    }

    /**
     * Return height of snapshot block
     *
     * @return Height of snapshot block
     */
    public Long getHeight() {
        return height;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    /**
     * Return snapshot block producer
     *
     * @return Snapshot block producer
     */
    public Address getProducer() {
        return Address.stringToAddress(producer);
    }

    public String getProducerRaw() {
        return producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    /**
     * Return producer's public key
     *
     * @return Producer's public key
     */
    public byte[] getPublicKey() {
        return BytesUtils.base64ToBytes(publicKey);
    }

    public String getPublicKeyRaw() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * Return signature
     *
     * @return Signature
     */
    public byte[] getSignature() {
        return BytesUtils.base64ToBytes(signature);
    }

    public String getSignatureRaw() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Return random seed generated by the same producer in prior round
     *
     * @return Random seed generated by the same producer in prior round
     */
    public BigInteger getSeed() {
        return seed;
    }

    public void setSeed(BigInteger seed) {
        this.seed = seed;
    }

    /**
     * Return hash of random seed generated in current round
     *
     * @return Hash of random seed generated in current round
     */
    public Hash getNextSeedHash() {
        return Hash.stringToHash(nextSeedHash);
    }

    public String getNextSeedHashRaw() {
        return nextSeedHash;
    }

    public void setNextSeedHash(String nextSeedHash) {
        this.nextSeedHash = nextSeedHash;
    }

    /**
     * Return producer code version
     *
     * @return Producer code version
     */
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Return snapshot content
     *
     * @return Snapshot content
     */
    public Map<Address, HashHeight> getSnapshotData() {
        if (snapshotData == null) {
            return null;
        }
        Map<Address, HashHeight> map = new HashMap<>(snapshotData.size());
        snapshotData.forEach((key, value) -> {
            map.put(new Address(key), value);
        });
        return map;
    }

    public Map<String, HashHeight> getSnapshotDataRaw() {
        return snapshotData;
    }

    public void setSnapshotData(Map<String, HashHeight> snapshotData) {
        this.snapshotData = snapshotData;
    }

    /**
     * Return timestamp of snapshot block produced
     *
     * @return Timestamp of snapshot block produced
     */
    public DateTime getTimestamp() {
        return TimeUtils.longToDateTime(timestamp);
    }

    public Long getTimestampRaw() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Block hash and height
     */
    public static class HashHeight {
        private Long height;
        private String hash;

        /**
         * Return height of block
         *
         * @return Height of block
         */
        public Long getHeight() {
            return height;
        }

        public void setHeight(Long height) {
            this.height = height;
        }

        /**
         * Return hash of block
         *
         * @return Hash of block
         */
        public Hash getHash() {
            return Hash.stringToHash(hash);
        }

        public String getHashRaw() {
            return hash;
        }

        public void setHash(String hash) {
            this.hash = hash;
        }
    }
}
